language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install -r requirements.txt

script: pytest

env:
  global:
    CODECOV_TOKEN: 533930b3-1af3-4fce-bd55-a2021e7f931c

after_success:
  - bash <(curl -s https://codecov.io/bash)
