language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install -U tox

after_install:
  - tox -r ./

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
